// 136

const grocerylistItems = [
  {
    id: 100,
    isSelected: false,
    name: "Bread",
    dept: "Bakery",
    deleteAfterUse: false,
  },
  {
    id: 101,
    isSelected: false,
    name: "Cookies",
    dept: "Bakery",
    deleteAfterUse: false,
  },
  {
    id: 107,
    isSelected: false,
    name: "Cereal",
    dept: "Breakfast",
    deleteAfterUse: false,
  },
  {
    id: 108,
    isSelected: false,
    name: "Oatmeal",
    dept: "Breakfast",
    deleteAfterUse: false,
  },
  {
    id: 109,
    isSelected: false,
    name: "Pop Tarts",
    dept: "Breakfast",
    deleteAfterUse: false,
  },
  {
    id: 127,
    isSelected: false,
    name: "Pasta Salad",
    dept: "Canned & Boxed",
    deleteAfterUse: false,
  },
  {
    id: 128,
    isSelected: false,
    name: "Peas",
    dept: "Canned & Boxed",
    deleteAfterUse: false,
  },
  {
    id: 131,
    isSelected: false,
    name: "Fruit",
    dept: "Canned & Boxed",
    deleteAfterUse: false,
  },
  {
    id: 132,
    isSelected: false,
    name: "Beans",
    dept: "Canned & Boxed",
    deleteAfterUse: false,
  },
  {
    id: 102,
    isSelected: false,
    name: "Milk",
    dept: "Dairy",
    deleteAfterUse: false,
  },
  {
    id: 103,
    isSelected: false,
    name: "Creamer",
    dept: "Dairy",
    deleteAfterUse: false,
  },
  {
    id: 104,
    isSelected: false,
    name: "Yogurt",
    dept: "Dairy",
    deleteAfterUse: false,
  },
  {
    id: 105,
    isSelected: false,
    name: "Cheese Slices",
    dept: "Dairy",
    deleteAfterUse: false,
  },
  {
    id: 106,
    isSelected: false,
    name: "Cheese Block",
    dept: "Dairy",
    deleteAfterUse: false,
  },
  {
    id: 135,
    isSelected: false,
    name: "Water",
    dept: "Drinks",
    deleteAfterUse: false,
  },
  {
    id: 122,
    isSelected: false,
    name: "Salsa",
    dept: "Ethnic",
    deleteAfterUse: false,
  },
  {
    id: 123,
    isSelected: false,
    name: "Queso",
    dept: "Ethnic",
    deleteAfterUse: false,
  },
  {
    id: 124,
    isSelected: false,
    name: "Corn Chips",
    dept: "Ethnic",
    deleteAfterUse: false,
  },
  {
    id: 125,
    isSelected: false,
    name: "Pasta",
    dept: "Ethnic",
    deleteAfterUse: false,
  },
  {
    id: 126,
    isSelected: false,
    name: "Spaghetti Sauce",
    dept: "Ethnic",
    deleteAfterUse: false,
  },
  {
    id: 128,
    isSelected: false,
    name: "Raman",
    dept: "Ethnic",
    deleteAfterUse: false,
  },
  {
    id: 133,
    isSelected: false,
    name: "Tomato Paste",
    dept: "Ethnic",
    deleteAfterUse: false,
  },
  {
    id: 116,
    isSelected: false,
    name: "Pizza",
    dept: "Frozen",
    deleteAfterUse: false,
  },
  {
    id: 117,
    isSelected: false,
    name: "Meals",
    dept: "Frozen",
    deleteAfterUse: false,
  },
  {
    id: 118,
    isSelected: false,
    name: "Ice Cream",
    dept: "Frozen",
    deleteAfterUse: false,
  },
  {
    id: 119,
    isSelected: false,
    name: "Fries",
    dept: "Frozen",
    deleteAfterUse: false,
  },
  {
    id: 120,
    isSelected: false,
    name: "Breakfast Bowl",
    dept: "Frozen",
    deleteAfterUse: false,
  },
  {
    id: 121,
    isSelected: false,
    name: "Vegetables",
    dept: "Frozen",
    deleteAfterUse: false,
  },
  {
    id: 114,
    isSelected: false,
    name: "Hamburger",
    dept: "Meat",
    deleteAfterUse: false,
  },
  {
    id: 115,
    isSelected: false,
    name: "Lunch Meat",
    dept: "Meat",
    deleteAfterUse: false,
  },
  {
    id: 129,
    isSelected: false,
    name: "Bar Soap",
    dept: "Pharmacy",
    deleteAfterUse: false,
  },
  {
    id: 130,
    isSelected: false,
    name: "Melatonin",
    dept: "Pharmacy",
    deleteAfterUse: false,
  },
  {
    id: 112,
    isSelected: false,
    name: "Bananas",
    dept: "Produce",
    deleteAfterUse: false,
  },
  {
    id: 113,
    isSelected: false,
    name: "Apples",
    dept: "Produce",
    deleteAfterUse: false,
  },
  {
    id: 110,
    isSelected: false,
    name: "Chips",
    dept: "Snacks",
    deleteAfterUse: false,
  },
  {
    id: 111,
    isSelected: false,
    name: "Peanuts",
    dept: "Snacks",
    deleteAfterUse: false,
  },
  {
    id: 134,
    isSelected: false,
    name: "Trail Mix",
    dept: "Snacks",
    deleteAfterUse: false,
  },
];

export default grocerylistItems;
